apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-visits
  labels:
    app: petclinic-visits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-visits
  template:
    metadata:
      labels:
        app: petclinic-visits
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: visits-service
          image: <path:petclinic/inputs#AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/petclinic-visits:sha-a56ae11
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: mysql
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-common
                  key: DB_HOST
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://$(DB_HOST)/visits_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-microservice-creds
                  key: VISITS_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-microservice-creds
                  key: VISITS_DATASOURCE_PASSWORD
            # 1. Tempo(Zipkin) 엔드포인트: 트레이스 데이터를 보낼 주소
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://monitoring-tempo.monitoring.svc.cluster.local:9411/api/v2/spans"
            
            # 2. 샘플링 비율: 1.0은 모든 요청을 수집함을 의미
            - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
              value: "1.0"

            # 3. 로그 포맷: [서비스명, TraceID, SpanID]가 로그에 찍히도록 설정
            # 이 포맷이 Loki의 Regex와 일치해야 로그에서 트레이스로 바로 점프 가능
            - name: LOGGING_PATTERN_LEVEL
              value: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

            # 4. Prometheus Exemplars 활성화: 그래프에서 트레이스 ID를 심어주는 설정
            # - name: MANAGEMENT_METRICS_DISTRIBUTION_PERCENTILES_HISTOGRAM_ALL
            #   value: "true"
            - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_EXEMPLARS_ENABLED
              value: "true"

              # 2. SLO 버킷 (선택 사항)
            - name: MANAGEMENT_METRICS_DISTRIBUTION_SLO_HTTP_SERVER_REQUESTS
              value: "10ms,50ms,100ms,200ms,500ms,1s,2s"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "512Mi"
              cpu: "400m"
            limits:
              memory: "1.5Gi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-visits
  labels:
    app: petclinic-visits
spec:
  type: ClusterIP
  selector:
    app: petclinic-visits
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080

