apiVersion: v2
name: monitoring
description: A Helm chart for monitoring
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: loki
    version: 6.6.0 # 최신 버전 확인
    repository: https://grafana.github.io/helm-charts
  - name: promtail
    version: 6.15.0
    repository: https://grafana.github.io/helm-charts