apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-frontend
  labels:
    app: petclinic-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-frontend
  template:
    metadata:
      labels:
        app: petclinic-frontend
    spec:
      containers:
        - name: frontend
          image: <path:petclinic/inputs#AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/petclinic-frontend:v5.0.9
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          env:
            # 1. Tempo(Zipkin) 엔드포인트: 트레이스 데이터를 보낼 주소
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://tempo.monitoring.svc.cluster.local:9411/api/v2/spans"
            
            # 2. 샘플링 비율: 1.0은 모든 요청을 수집함을 의미
            - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
              value: "1.0"

            # 3. 로그 포맷: [서비스명, TraceID, SpanID]가 로그에 찍히도록 설정
            # 이 포맷이 Loki의 Regex와 일치해야 로그에서 트레이스로 바로 점프 가능
            - name: LOGGING_PATTERN_LEVEL
              value: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

            # 4. Prometheus Exemplars 활성화: 그래프에서 트레이스 ID를 심어주는 설정
            - name: MANAGEMENT_METRICS_DISTRIBUTION_PERCENTILES_HISTOGRAM_ALL
              value: "true"
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-frontend
  labels:
    app: petclinic-frontend
spec:
  type: ClusterIP
  selector:
    app: petclinic-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http

